AWSTemplateFormatVersion: 2010-09-09

Parameters:
  NameTag:
    Type: String
    Default: dev

Resources:
  testBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: "Name"
          Value: !Ref NameTag
